{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyrebase4 in d:\\anaconda\\lib\\site-packages (4.5.0)\n",
      "Requirement already satisfied: oauth2client>=4.1.2 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (4.1.3)\n",
      "Requirement already satisfied: gcloud>=0.18.3 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (0.18.3)\n",
      "Requirement already satisfied: pycryptodome>=3.6.4 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (3.10.1)\n",
      "Requirement already satisfied: requests>=2.19.1 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (2.24.0)\n",
      "Requirement already satisfied: requests-toolbelt>=0.7.1 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (0.9.1)\n",
      "Requirement already satisfied: python-jwt>=2.0.1 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (3.3.0)\n",
      "Requirement already satisfied: rsa>=3.1.4 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (4.7.2)\n",
      "Requirement already satisfied: httplib2>=0.9.1 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (0.19.1)\n",
      "Requirement already satisfied: pyasn1-modules>=0.0.5 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (0.2.8)\n",
      "Requirement already satisfied: six>=1.6.1 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (1.15.0)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (0.4.8)\n",
      "Requirement already satisfied: googleapis-common-protos in d:\\anaconda\\lib\\site-packages (from gcloud>=0.18.3->pyrebase4) (1.53.0)\n",
      "Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in d:\\anaconda\\lib\\site-packages (from gcloud>=0.18.3->pyrebase4) (3.15.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (2020.6.20)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (3.0.4)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (1.25.11)\n",
      "Requirement already satisfied: idna<3,>=2.5 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (2.10)\n",
      "Requirement already satisfied: jwcrypto>=0.8 in d:\\anaconda\\lib\\site-packages (from python-jwt>=2.0.1->pyrebase4) (0.9.1)\n",
      "Requirement already satisfied: pyparsing<3,>=2.4.2 in d:\\anaconda\\lib\\site-packages (from httplib2>=0.9.1->oauth2client>=4.1.2->pyrebase4) (2.4.7)\n",
      "Requirement already satisfied: cryptography>=2.3 in d:\\anaconda\\lib\\site-packages (from jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (3.1.1)\n",
      "Requirement already satisfied: deprecated in d:\\anaconda\\lib\\site-packages (from jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (1.2.12)\n",
      "Requirement already satisfied: cffi!=1.11.3,>=1.8 in d:\\anaconda\\lib\\site-packages (from cryptography>=2.3->jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (1.14.3)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in d:\\anaconda\\lib\\site-packages (from deprecated->jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (1.12.1)\n",
      "Requirement already satisfied: pycparser in d:\\anaconda\\lib\\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (2.20)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pyrebase4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyrebase import pyrebase"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyrebase4 in d:\\anaconda\\lib\\site-packages (4.5.0)\n",
      "Requirement already satisfied: pycryptodome>=3.6.4 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (3.10.1)\n",
      "Requirement already satisfied: requests>=2.19.1 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (2.24.0)\n",
      "Requirement already satisfied: requests-toolbelt>=0.7.1 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (0.9.1)\n",
      "Requirement already satisfied: python-jwt>=2.0.1 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (3.3.0)\n",
      "Requirement already satisfied: oauth2client>=4.1.2 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (4.1.3)\n",
      "Requirement already satisfied: gcloud>=0.18.3 in d:\\anaconda\\lib\\site-packages (from pyrebase4) (0.18.3)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (1.25.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (2020.6.20)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (3.0.4)\n",
      "Requirement already satisfied: idna<3,>=2.5 in d:\\anaconda\\lib\\site-packages (from requests>=2.19.1->pyrebase4) (2.10)\n",
      "Requirement already satisfied: jwcrypto>=0.8 in d:\\anaconda\\lib\\site-packages (from python-jwt>=2.0.1->pyrebase4) (0.9.1)\n",
      "Requirement already satisfied: pyasn1>=0.1.7 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (0.4.8)\n",
      "Requirement already satisfied: six>=1.6.1 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (1.15.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.0.5 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (0.2.8)\n",
      "Requirement already satisfied: rsa>=3.1.4 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (4.7.2)\n",
      "Requirement already satisfied: httplib2>=0.9.1 in d:\\anaconda\\lib\\site-packages (from oauth2client>=4.1.2->pyrebase4) (0.19.1)\n",
      "Requirement already satisfied: protobuf!=3.0.0.b2.post1,>=3.0.0b2 in d:\\anaconda\\lib\\site-packages (from gcloud>=0.18.3->pyrebase4) (3.15.7)\n",
      "Requirement already satisfied: googleapis-common-protos in d:\\anaconda\\lib\\site-packages (from gcloud>=0.18.3->pyrebase4) (1.53.0)\n",
      "Requirement already satisfied: deprecated in d:\\anaconda\\lib\\site-packages (from jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (1.2.12)\n",
      "Requirement already satisfied: cryptography>=2.3 in d:\\anaconda\\lib\\site-packages (from jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (3.1.1)\n",
      "Requirement already satisfied: pyparsing<3,>=2.4.2 in d:\\anaconda\\lib\\site-packages (from httplib2>=0.9.1->oauth2client>=4.1.2->pyrebase4) (2.4.7)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in d:\\anaconda\\lib\\site-packages (from deprecated->jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (1.12.1)\n",
      "Requirement already satisfied: cffi!=1.11.3,>=1.8 in d:\\anaconda\\lib\\site-packages (from cryptography>=2.3->jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (1.14.3)\n",
      "Requirement already satisfied: pycparser in d:\\anaconda\\lib\\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->jwcrypto>=0.8->python-jwt>=2.0.1->pyrebase4) (2.20)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pyrebase4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pyrebase"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "config = {\n",
    "  \"apiKey\": \"AIzaSyAVwr-sPn0QJs1COqzf-UWPu3cf2oVbkNQ\",\n",
    "  \"authDomain\": \"psychological-server.firebaseapp.com\",\n",
    "  \"databaseURL\": \"https://psychological-server-default-rtdb.firebaseio.com/\",\n",
    "  \"projectId\": \"psychological-server\",\n",
    "  \"storageBucket\": \"psychological-server.appspot.com\",\n",
    "  \"messagingSenderId\": \"161316158562\",\n",
    "  \"appId\": \"1:161316158562:web:339d81f51b6e268470a53b\"\n",
    "}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "firebase = pyrebase.initialize_app(config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<pyrebase.pyrebase.Firebase at 0x18e3ed6bc40>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "firebase"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: firebase_admin in d:\\anaconda\\lib\\site-packages (5.0.1)\n",
      "Requirement already satisfied: google-cloud-firestore>=2.1.0; platform_python_implementation != \"PyPy\" in d:\\anaconda\\lib\\site-packages (from firebase_admin) (2.1.3)\n",
      "Requirement already satisfied: google-api-python-client>=1.7.8 in d:\\anaconda\\lib\\site-packages (from firebase_admin) (2.9.0)\n",
      "Requirement already satisfied: cachecontrol>=0.12.6 in d:\\anaconda\\lib\\site-packages (from firebase_admin) (0.12.6)\n",
      "Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.22.1; platform_python_implementation != \"PyPy\" in d:\\anaconda\\lib\\site-packages (from firebase_admin) (1.30.0)\n",
      "Requirement already satisfied: google-cloud-storage>=1.37.1 in d:\\anaconda\\lib\\site-packages (from firebase_admin) (1.38.0)\n",
      "Requirement already satisfied: packaging>=14.3 in d:\\anaconda\\lib\\site-packages (from google-cloud-firestore>=2.1.0; platform_python_implementation != \"PyPy\"->firebase_admin) (20.4)\n",
      "Requirement already satisfied: pytz in d:\\anaconda\\lib\\site-packages (from google-cloud-firestore>=2.1.0; platform_python_implementation != \"PyPy\"->firebase_admin) (2020.1)\n",
      "Requirement already satisfied: proto-plus>=1.10.0 in d:\\anaconda\\lib\\site-packages (from google-cloud-firestore>=2.1.0; platform_python_implementation != \"PyPy\"->firebase_admin) (1.18.1)\n",
      "Requirement already satisfied: google-cloud-core<2.0dev,>=1.4.1 in d:\\anaconda\\lib\\site-packages (from google-cloud-firestore>=2.1.0; platform_python_implementation != \"PyPy\"->firebase_admin) (1.7.0)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in d:\\anaconda\\lib\\site-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.19.1)\n",
      "Requirement already satisfied: uritemplate<4dev,>=3.0.0 in d:\\anaconda\\lib\\site-packages (from google-api-python-client>=1.7.8->firebase_admin) (3.0.1)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.1.0 in d:\\anaconda\\lib\\site-packages (from google-api-python-client>=1.7.8->firebase_admin) (0.1.0)\n",
      "Requirement already satisfied: six<2dev,>=1.13.0 in d:\\anaconda\\lib\\site-packages (from google-api-python-client>=1.7.8->firebase_admin) (1.15.0)\n",
      "Requirement already satisfied: google-auth<2dev,>=1.16.0 in d:\\anaconda\\lib\\site-packages (from google-api-python-client>=1.7.8->firebase_admin) (1.28.0)\n",
      "Requirement already satisfied: requests in d:\\anaconda\\lib\\site-packages (from cachecontrol>=0.12.6->firebase_admin) (2.24.0)\n",
      "Requirement already satisfied: msgpack>=0.5.2 in d:\\anaconda\\lib\\site-packages (from cachecontrol>=0.12.6->firebase_admin) (1.0.0)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in d:\\anaconda\\lib\\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.1; platform_python_implementation != \"PyPy\"->firebase_admin) (50.3.1.post20201107)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in d:\\anaconda\\lib\\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.1; platform_python_implementation != \"PyPy\"->firebase_admin) (1.53.0)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in d:\\anaconda\\lib\\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.1; platform_python_implementation != \"PyPy\"->firebase_admin) (3.15.7)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.29.0; extra == \"grpc\" in d:\\anaconda\\lib\\site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.1; platform_python_implementation != \"PyPy\"->firebase_admin) (1.32.0)\n",
      "Requirement already satisfied: google-resumable-media<2.0dev,>=1.2.0 in d:\\anaconda\\lib\\site-packages (from google-cloud-storage>=1.37.1->firebase_admin) (1.3.1)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in d:\\anaconda\\lib\\site-packages (from packaging>=14.3->google-cloud-firestore>=2.1.0; platform_python_implementation != \"PyPy\"->firebase_admin) (2.4.7)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4; python_version >= \"3.6\" in d:\\anaconda\\lib\\site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client>=1.7.8->firebase_admin) (4.7.2)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in d:\\anaconda\\lib\\site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client>=1.7.8->firebase_admin) (4.2.1)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\\anaconda\\lib\\site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client>=1.7.8->firebase_admin) (0.2.8)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\\anaconda\\lib\\site-packages (from requests->cachecontrol>=0.12.6->firebase_admin) (1.25.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in d:\\anaconda\\lib\\site-packages (from requests->cachecontrol>=0.12.6->firebase_admin) (2020.6.20)\n",
      "Requirement already satisfied: idna<3,>=2.5 in d:\\anaconda\\lib\\site-packages (from requests->cachecontrol>=0.12.6->firebase_admin) (2.10)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in d:\\anaconda\\lib\\site-packages (from requests->cachecontrol>=0.12.6->firebase_admin) (3.0.4)\n",
      "Requirement already satisfied: google-crc32c<2.0dev,>=1.0; python_version >= \"3.5\" in d:\\anaconda\\lib\\site-packages (from google-resumable-media<2.0dev,>=1.2.0->google-cloud-storage>=1.37.1->firebase_admin) (1.1.2)\n",
      "Requirement already satisfied: pyasn1>=0.1.3 in d:\\anaconda\\lib\\site-packages (from rsa<5,>=3.1.4; python_version >= \"3.6\"->google-auth<2dev,>=1.16.0->google-api-python-client>=1.7.8->firebase_admin) (0.4.8)\n",
      "Requirement already satisfied: cffi>=1.0.0 in d:\\anaconda\\lib\\site-packages (from google-crc32c<2.0dev,>=1.0; python_version >= \"3.5\"->google-resumable-media<2.0dev,>=1.2.0->google-cloud-storage>=1.37.1->firebase_admin) (1.14.3)\n",
      "Requirement already satisfied: pycparser in d:\\anaconda\\lib\\site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0; python_version >= \"3.5\"->google-resumable-media<2.0dev,>=1.2.0->google-cloud-storage>=1.37.1->firebase_admin) (2.20)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install firebase_admin"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import firebase_admin\n",
    "from firebase_admin import credentials\n",
    "from firebase_admin import db"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "The default Firebase app already exists. This means you called initialize_app() more than once without providing an app name as the second argument. In most cases you only need to call initialize_app() once. But if you do want to initialize multiple apps, pass a second argument to initialize_app() to give each app a unique name.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-17-af2a47780b26>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     14\u001b[0m \u001b[1;31m# 인증 및 앱 초기화\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     15\u001b[0m \u001b[0mcred\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcredentials\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mCertificate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"CBTI_Key.json\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 16\u001b[1;33m firebase_admin.initialize_app(cred,\n\u001b[0m\u001b[0;32m     17\u001b[0m                              {'databaseURL' : db_url})\n",
      "\u001b[1;32mD:\\Anaconda\\lib\\site-packages\\firebase_admin\\__init__.py\u001b[0m in \u001b[0;36minitialize_app\u001b[1;34m(credential, options, name)\u001b[0m\n\u001b[0;32m     69\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     70\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mname\u001b[0m \u001b[1;33m==\u001b[0m \u001b[0m_DEFAULT_APP_NAME\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 71\u001b[1;33m         raise ValueError((\n\u001b[0m\u001b[0;32m     72\u001b[0m             \u001b[1;34m'The default Firebase app already exists. This means you called '\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     73\u001b[0m             \u001b[1;34m'initialize_app() more than once without providing an app name as '\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: The default Firebase app already exists. This means you called initialize_app() more than once without providing an app name as the second argument. In most cases you only need to call initialize_app() once. But if you do want to initialize multiple apps, pass a second argument to initialize_app() to give each app a unique name."
     ]
    }
   ],
   "source": [
    "# test\n",
    "db_url = \"https://psychological-server-default-rtdb.firebaseio.com/\"\n",
    "\n",
    "config = {\n",
    "  \"apiKey\": \"AIzaSyAVwr-sPn0QJs1COqzf-UWPu3cf2oVbkNQ\",\n",
    "  \"authDomain\": \"psychological-server.firebaseapp.com\",\n",
    "  \"databaseURL\": \"https://psychological-server-default-rtdb.firebaseio.com/\",\n",
    "  \"projectId\": \"psychological-server\",\n",
    "  \"storageBucket\": \"psychological-server.appspot.com\",\n",
    "  \"messagingSenderId\": \"161316158562\",\n",
    "  \"appId\": \"1:161316158562:web:339d81f51b6e268470a53b\"\n",
    "}\n",
    "\n",
    "# 인증 및 앱 초기화\n",
    "cred = credentials.Certificate(\"CBTI_Key.json\")\n",
    "firebase_admin.initialize_app(cred,\n",
    "                             {'databaseURL' : db_url})\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'pyrebase' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-18-76110142e881>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mfirebase\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpyrebase\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minitialize_app\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconfig\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[0mfb_db\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfirebase\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdatabase\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m user_info = {\n\u001b[0;32m      4\u001b[0m     \u001b[1;34m\"USER_ID\"\u001b[0m \u001b[1;33m:\u001b[0m \u001b[1;34m\"아이디\"\u001b[0m \u001b[1;34m\"중복불가\"\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m     \u001b[1;34m\"USER_PW\"\u001b[0m \u001b[1;33m:\u001b[0m \u001b[1;34m\"패스워드\"\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'pyrebase' is not defined"
     ]
    }
   ],
   "source": [
    "firebase = pyrebase.initialize_app(config)\n",
    "fb_db = firebase.database()\n",
    "user_info = {\n",
    "    \"USER_ID\" : \"아이디\" \"중복불가\",\n",
    "    \"USER_PW\" : \"패스워드\",\n",
    "    \"USER_NM\" : \"유저명\" \" 및 \" \"닉네임\",\n",
    "    \"USER_TP\" : \"유저타입\"  \"  \" \"A = AUTHOR\" \" \" \"D = DEVELPOER\",\n",
    "    \"REG_DT\" : \"가입일자\"\n",
    "}\n",
    "\n",
    "ref = db.reference()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "ref = db.reference('회원정보')\n",
    "ref.update({\"USER_ID\" : \"아이디\" \"중복불가\",\n",
    "    \"USER_PW\" : \"패스워드\",\n",
    "    \"USER_NM\" : \"유저명\" \" 및 \" \"닉네임\",\n",
    "    \"USER_TP\" : \"유저타입\"  \"  \" \"A = AUTHOR\" \" \" \"D = DEVELPOER\",\n",
    "    \"REG_DT\" : \"가입일자\"})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "ref = db.reference('심리테스트')\n",
    "ref.update({\n",
    "    \"TEST_NO\" : \"중복불가\",\n",
    "    \"TEST_DESC\" : \"테스트 설명\",\n",
    "    \"TEST_AUTHOR\" : \"작가명\",\n",
    "    \"RELEASE_DATE\" : \"출시일\"\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "f5d09742-bd84-49e6-bb61-ab4c16e92c76\n"
     ]
    }
   ],
   "source": [
    "import uuid\n",
    "print(uuid.uuid4())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "ref = db.reference('심리테스트 결과')\n",
    "ref.update({\n",
    "    \"UUID\" : \"f5d09742bd8449e6bb61ab4c16e92c76\",\n",
    "    \"RES_CD\" : \"결과\" \"  \" \"ex) ISTJ - 0 INTJ - 1 이런식으로 코드 매겨서 저장\",\n",
    "    \"START_TM\" : \"시작시간\" \"  \" \"시작버튼 누를때 체크\", \n",
    "    \"END_TM\" : \"종료시간\" \"  \"  \"종료버튼 누를때 체크\",\n",
    "    \"TEST_YN\" : \"완료여부\"  \"  \"  \"최초 시작버튼 누를땐 N, 결과버튼 누를시 Y \",\n",
    "    \"TEST_NO\" : \"테스트 번호\"\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<firebase_admin.db.Reference at 0x1a6c57b3490>"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ref = db.reference(\"회원정보\")\n",
    "ref.push({\n",
    "    'id' : 'user1', \n",
    "    'password' : 'pw11'\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<firebase_admin.db.Reference at 0x1a6c67c4100>"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# push 하면 고유id와 함께 데이터 삽입\n",
    "# ref = db.reference(\"회원정보\")\n",
    "# ref.push({\n",
    "#     'id' : 'user2', \n",
    "#     'password' : 'pw22'\n",
    "# })\n",
    "# ref.push({\n",
    "#     'id' : 'user3', \n",
    "#     'password' : 'pw33'\n",
    "# })\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "users = db.reference(\"회원정보\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
